from test_visual_status import test, tests

test('Additional game sounds require available client constants', "SOUNDKIT={TELL_MESSAGE=3081,ALARM_CLOCK_WARNING_1=18871,ALARM_CLOCK_WARNING_3=12889,IG_QUEST_LIST_COMPLETE=878}; local c=BuffTap:SoundChoices(); assert(#c==5); local heard; PlaySound=function(id) heard=id; return true end; BuffTap.db.reminderSound='whisper'; assert(BuffTap:PlayAlert('reminder',true) and heard==3081)")
test('SharedMedia optional absence preserves preference and falls back', "BuffTap.db.reminderSound='lsm:Bell'; BuffTap:NormalizeAlerts(); assert(BuffTap.db.reminderSound=='lsm:Bell'); local heard; PlaySound=function(id) heard=id; return true end; assert(BuffTap:PlayAlert('reminder',true) and heard==12867); local c=BuffTap:SoundChoices(); assert(c[#c].name:find('unavailable',1,true))")
test('Late media registration is available without polling or reload', "BuffTap.db.reminderSound='lsm:Bell'; local media={}; LibStub=function(name) assert(name=='LibSharedMedia-3.0'); return {HashTable=function() return media end} end; local heard; PlaySoundFile=function(v,c) heard={v,c}; return true end; media.Bell='Interface/AddOns/Test/Bell.ogg'; assert(BuffTap:PlayAlert('reminder',true)); assert(heard[1]==media.Bell and heard[2]=='Master' and not BuffTap.lastAlertSound)")
test('SharedMedia supports FileDataIDs and separate supply selection', "LibStub=function() return {HashTable=function() return {Bell=12345,None=1} end} end; local c=BuffTap:SoundChoices(); assert(#c==2 and c[2].key=='lsm:Bell'); local heard; PlaySoundFile=function(v,channel) heard={v,channel}; return true end; BuffTap.db.supplySound='lsm:Bell'; BuffTap.db.soundChannel='SFX'; assert(BuffTap:PlayAlert('supply',true)); assert(heard[1]==12345 and heard[2]=='SFX' and BuffTap.db.reminderSound=='default')")
test('Unavailable or failed media plays default without consuming preview cooldown', "LibStub=function() return {HashTable=function() return {Bell='bad.ogg'} end} end; PlaySoundFile=function() return false end; local heard; PlaySound=function(v) heard=v; return true end; BuffTap.db.reminderSound='lsm:Bell'; assert(BuffTap:PlayAlert('reminder',true) and heard==12867 and not BuffTap.lastAlertSound)")
test('Malformed library is contained and preserves gameplay', "LibStub=function() error('library unavailable') end; local id=BuffTap.action.id; assert(#BuffTap:SoundChoices()==1); assert(BuffTap:PlayAlert('reminder',true) and BuffTap.action.id==id)")
test('Sound chooser scrolls large registries and search filters without paging', "local media={}; for i=1,100 do media['Bell '..i]='test.ogg' end; LibStub=function() return {HashTable=function() return media end} end; BuffTap:Options(); local b=BuffTap.options.reminderSoundButton; b.scripts.OnClick(); assert(#b.menu.rows==101 and b.menu.scroll and b.menu.content and not b.menu.next and not b.menu.previous and BuffTap.db.reminderSound=='default'); b.menu.search:SetText('Bell 99'); b.menu.search.scripts.OnTextChanged(); assert(b.menu.rows[1].choice=='lsm:Bell 99' and not b.menu.rows[2].shown); b.menu.rows[1].scripts.OnClick(b.menu.rows[1]); assert(BuffTap.db.reminderSound=='lsm:Bell 99' and not b.menu.shown)")
test('Media alerts retain shared rate limiting and pause rules', "LibStub=function() return {HashTable=function() return {Bell='test.ogg'} end} end; local n=0; PlaySoundFile=function() n=n+1; return true end; BuffTap.db.reminderSound='lsm:Bell'; BuffTap.db.sound=true; assert(BuffTap:PlayAlert('reminder')); assert(not BuffTap:PlayAlert('reminder') and n==1); mounted=true; now=now+60; assert(not BuffTap:PlayAlert('reminder') and n==1)")
print('ALL',len(tests),'SCENARIOS PASSED')
