from test_usability import test, tests, ROOT

test('Minimap enabled but no broker object registered by default', "assert(not BuffTap.db.minimap.hide and not BuffTap.db.brokerEnabled); assert(LibStub('LibDBIcon-1.0'):IsRegistered('BuffTap')); assert(not LibStub('LibDataBroker-1.1'):GetDataObjectByName('BuffTap'))")
test('Opt-in broker reuses cached status without selecting or scanning', "BuffTap.Select=function() error('scan') end; BuffTap.db.brokerEnabled=true; BuffTap:SyncBroker(); local o=BuffTap.brokerObject; assert(o.type=='data source' and o.text==BuffTap:FriendlyStatus()); BuffTap:UpdateBroker(); assert(BuffTap.brokerObject==o)")
test('Minimap hide is independent of broker display', "BuffTap.db.brokerEnabled=true; BuffTap.db.minimap.hide=true; BuffTap:SyncBroker(); assert(BuffTap.brokerObject and not LibStub('LibDBIcon-1.0'):GetMinimapButton('BuffTap'):IsShown()); BuffTap.db.minimap.hide=false; BuffTap:SyncBroker(); assert(LibStub('LibDBIcon-1.0'):GetMinimapButton('BuffTap'):IsShown())")
test('Reset replaces library saved-variable reference safely', "local old=BuffTap.db.minimap; BuffTapDB={minimap={hide=true,minimapPos=0/0},brokerEnabled='bad'}; BuffTap:InitDB(); local b=LibStub('LibDBIcon-1.0'):GetMinimapButton('BuffTap'); assert(b.db==BuffTap.db.minimap and b.db~=old and b.db.minimapPos==225 and not BuffTap.db.brokerEnabled)")
test('Broker clearing follows combat without protected mutations', "BuffTap.db.brokerEnabled=true; BuffTap:SyncBroker(); combat=true; safety('blocked'); BuffTap.events.scripts.OnEvent(nil,'PLAYER_REGEN_DISABLED'); assert(not BuffTap.action and BuffTap.brokerObject.text==BuffTap:FriendlyStatus()); local action=BuffTap.action; BuffTap.brokerObject.OnClick(); assert(BuffTap.action==action and not BuffTap.options)")
test('Broker disable shows reload status and resets to absent after reload', "BuffTap.db.brokerEnabled=true; BuffTap:SyncBroker(); BuffTap.db.brokerEnabled=false; BuffTap:SyncBroker(); assert(BuffTap.brokerObject.text==BuffTap:Text('Broker disabled — reload UI'))")
test('Minimap idle has no update loop and click opens settings', "local b=LibStub('LibDBIcon-1.0'):GetMinimapButton('BuffTap'); assert(not b.scripts.OnUpdate); b.dataObject.OnClick(); assert(BuffTap.options:IsShown()); b.dataObject.OnClick(); assert(not BuffTap.options:IsShown())")
test('Quick access controls reflect independent preferences', "BuffTap:Options(); assert(BuffTap.options.minimapCheck:GetChecked() and not BuffTap.options.brokerCheck:GetChecked())")
print(f'ALL {len(tests)} SCENARIOS PASSED')
(ROOT/'tests/regression-minimap-latest.txt').write_text('\n'.join('PASS '+n for n in tests)+f'\n{len(tests)} mocked Lua 5.1 scenarios passed. Live minimap/broker compatibility pending.\n',encoding='utf-8')
