from test_ordered_blessings import test, tests

test('Opening a sound selector does not change its preference', "SOUNDKIT={READY_CHECK=8960}; BuffTap:Options(); local f=BuffTap.options; f.reminderSoundButton.scripts.OnClick(); assert(BuffTap.db.reminderSound=='default' and f.reminderSoundButton.menu.shown); f.reminderSoundButton.scripts.OnClick(); assert(not f.reminderSoundButton.menu.shown and BuffTap.db.reminderSound=='default')")
test('Sound selection remains independent of supply sound', "SOUNDKIT={READY_CHECK=8960}; BuffTap:Options(); local f=BuffTap.options; f.reminderSoundButton.scripts.OnClick(); local row=f.reminderSoundButton.menu.rows[2]; row.scripts.OnClick(row); assert(BuffTap.db.reminderSound=='ready' and BuffTap.db.supplySound=='default' and not f.reminderSoundButton.menu.shown)")
test('Opening another selector closes the first', "BuffTap:Options(); local f=BuffTap.options; f.reminderSoundButton.scripts.OnClick(); f.channelButton.scripts.OnClick(); assert(not f.reminderSoundButton.menu.shown and f.channelButton.menu.shown)")
test('Changing tabs closes an open selector', "BuffTap:Options(); local f=BuffTap.options; f.channelButton.scripts.OnClick(); f.selectTab(1); assert(not f.channelButton.menu.shown)")
test('Closing options closes an open selector', "BuffTap:Options(); local f=BuffTap.options; f.channelButton.scripts.OnClick(); f:Hide(); assert(not f.channelButton.menu.shown)")
test('Combat cannot change a sound preference', "SOUNDKIT={READY_CHECK=8960}; BuffTap:Options(); local f=BuffTap.options; f.reminderSoundButton.scripts.OnClick(); local row=f.reminderSoundButton.menu.rows[2]; combat=true; row.scripts.OnClick(row); assert(BuffTap.db.reminderSound=='default')")
test('Weapon mode selector preserves application opt-in', "BuffTap:Options(); local f=BuffTap.options; f.weaponApply.scripts.OnClick(); assert(not BuffTap.db.weaponApply); local row=f.weaponApply.menu.rows[2]; row.scripts.OnClick(row); assert(BuffTap.db.weaponApply and f.weaponApply.text=='Remind and apply'); f.weaponApply.scripts.OnClick(); row=f.weaponApply.menu.rows[1]; row.scripts.OnClick(row); assert(not BuffTap.db.weaponApply and f.weaponApply.text=='Remind only')")
test('Status distinguishes a manual alert from an actionable cast', "BuffTap.action={manual=true,name='Wizard Oil',target='player'}; assert(BuffTap:FriendlyStatus()=='Manual application: Wizard Oil'); BuffTap:Options(); assert(BuffTap.options.statusText.text==BuffTap:FriendlyStatus())")
test('Visible settings status updates without a broker display', "BuffTap:Options(); BuffTap.db.enabled=false; BuffTap:UpdateBroker(); assert(BuffTap.options.statusText.text=='BuffTap is disabled.' and not BuffTap.brokerObject)")
test('Customization exposes saving guidance without header Debug', "BuffTap:Options(); local f=BuffTap.options; assert(f.tabs[6].text=='Customization' and not f.debugButton and f.saveHint.text:find('Enter to save',1,true))")
test('Consumable help describes the actual family control', "GameTooltip={SetOwner=function() end,SetText=function(_,t) tooltipTitle=t end,AddLine=function(_,t) tooltipBody=t end,Show=function() end}; BuffTap:Options(); local c=BuffTap.options.consumableRows[1].enable; c.scripts.OnEnter(c); assert(tooltipTitle=='Maintain this consumable buff' and not tooltipBody:find('friendly target',1,true))")
for locale in ('esES','deDE','frFR','ptBR'):
    test('Customization tab localized '+locale,"BuffTap:Options(); assert(BuffTap.options.tabs[6].text~='Customization')",locale=locale)
print('ALL',len(tests),'SCENARIOS PASSED')
