from test_readiness import test

capture = "BuffTap:CaptureBinding(); local f=BuffTap.capture; "

test('Middle and side buttons capture and persist', capture + "for _,v in ipairs({{'MiddleButton','BUTTON3'},{'Button4','BUTTON4'},{'Button5','BUTTON5'}}) do BuffTap:CaptureBinding(); f.scripts.OnMouseDown(f,v[1]); assert(not f.shown and BuffTap.db.keys[1]==v[2]); BuffTap:InitDB(); assert(BuffTap.db.keys[1]==v[2]) end")
test('Plain primary clicks leave capture and binding unchanged', capture + "local before=BuffTap.db.keys[1]; f.scripts.OnMouseDown(f,'LeftButton'); f.scripts.OnMouseDown(f,'RightButton'); assert(f.shown and BuffTap.db.keys[1]==before)")
test('Modified primary clicks and side buttons preserve modifiers', capture + "IsShiftKeyDown=function() return true end; f.scripts.OnMouseDown(f,'LeftButton'); assert(BuffTap.db.keys[1]=='SHIFT-BUTTON1'); BuffTap:CaptureBinding(); IsShiftKeyDown=function() return false end; IsControlKeyDown=function() return true end; f.scripts.OnMouseDown(f,'RightButton'); assert(BuffTap.db.keys[1]=='CTRL-BUTTON2'); BuffTap:CaptureBinding(); IsAltKeyDown=function() return true end; IsShiftKeyDown=function() return true end; f.scripts.OnMouseDown(f,'Button5'); assert(BuffTap.db.keys[1]=='ALT-CTRL-SHIFT-BUTTON5')")
test('Escape cancels mouse capture without changing binding', capture + "local before=BuffTap.db.keys[1]; f.scripts.OnKeyDown(f,'ESCAPE'); assert(not f.shown and BuffTap.db.keys[1]==before)")
test('Combat cancels capture and rejects mouse binding changes', capture + "local before=BuffTap.db.keys[1]; combat=true; f.scripts.OnEvent(f,'PLAYER_REGEN_DISABLED'); assert(not f.shown); f.scripts.OnMouseDown(f,'Button5'); assert(BuffTap.db.keys[1]==before); BuffTap:CaptureBinding(); assert(not f.shown)")
test('Unknown mouse input leaves binding unchanged', capture + "local before=BuffTap.db.keys[1]; f.scripts.OnMouseDown(f,'UnknownButton'); f.scripts.OnMouseDown(f,nil); assert(f.shown and BuffTap.db.keys[1]==before)")
test('Side binding installs secure override and releases when satisfied', capture + "f.scripts.OnMouseDown(f,'Button5'); advance(.1); assert(bindings.BUTTON5 and not bindings.MOUSEWHEELDOWN); aura('player',5232,'Mark of the Wild'); aura('player',467,'Thorns'); refresh(); assert(not next(bindings))")
test('Side binding releases in combat and returns on exit', capture + "f.scripts.OnMouseDown(f,'Button4'); advance(.1); assert(bindings.BUTTON4); combat=true; safety('blocked'); BuffTap.events.scripts.OnEvent(nil,'PLAYER_REGEN_DISABLED'); assert(not next(bindings)); combat=false; safety('ready'); BuffTap.events.scripts.OnEvent(nil,'PLAYER_REGEN_ENABLED'); assert(bindings.BUTTON4)")
