from test_convenience import test, tests

test('Both windows load the same explicit TGA banner without changing the action', "local id=BuffTap.action.id; BuffTap:Options(); BuffTap:ShowWelcome(true); local f=BuffTap.options.banner; local w=BuffTap.welcome.banner; assert(f.art.texture==[[Interface\\AddOns\\BuffTap\\Media\\BuffTapMiniBanner.tga]] and f.art.texture==w.art.texture); assert(f.artWidth==600 and f.artHeight<124 and w.artWidth==528 and w.artHeight<109); assert(not f.title and not w.title and BuffTap.action.id==id and bindings.MOUSEWHEELDOWN)")
test('Onboarding explains buffing and still opens settings', "BuffTap:ShowWelcome(true); assert(#BuffTap.welcome.steps==3 and BuffTap.welcome.steps[2].text.text:find('scroll or click',1,true)); BuffTap.welcome.settingsButton.scripts.OnClick(); assert(BuffTap.options.shown and not BuffTap.welcome.shown)")
test('Onboarding preview remains harmless and dismissal remains persistent', "local id=BuffTap.action.id; BuffTap:ShowWelcome(true); BuffTap.welcome.previewButton.scripts.OnClick(); assert(BuffTap.appearancePreview.shown and not BuffTap.appearancePreview.protected and BuffTap.action.id==id); BuffTap:ShowWelcome(true); BuffTap.welcome.doneButton.scripts.OnClick(); assert(not BuffTap.welcome.shown and BuffTap.db.welcomeSeen)")
test('Branding cannot open or mutate secure actions during combat', "combat=true; safety('blocked'); BuffTap:Options(); BuffTap:ShowWelcome(true); assert(not BuffTap.options and not BuffTap.welcome and not BuffTap.button.attrs.type1)")
for locale in ['deDE','frFR','esES','ptBR']:
    test('Branded onboarding guidance translated '+locale, "BuffTap:ShowWelcome(true); assert(not BuffTap.welcome.steps[1].text.text:find('Choose your buffs',1,true) and BuffTap.welcome.body.text=='MOUSEWHEELDOWN')", locale=locale)
test('Ready status uses a client-safe separator', "BuffTap.action={name='Mark of the Wild',targetName='Dane'}; assert(BuffTap:FriendlyStatus()=='Ready: Mark of the Wild - Dane')")
test('Welcome dismisses selectors and other foreground windows', "BuffTap:Options(); local f=BuffTap.options; f.activeSelector=CreateFrame('Frame'); f.activeSelector:Show(); BuffTap.itemPicker=CreateFrame('Frame'); BuffTap.itemPicker:Show(); BuffTap:ShowQuickMenu(); assert(not f.activeSelector.shown and not BuffTap.itemPicker.shown); BuffTap:ShowWelcome(true); assert(BuffTap.welcome.shown and not BuffTap.quickMenu.shown and f.shown)")
test('Window roots use distinct strata and options are clamped and raised', "local make=CreateFrame; CreateFrame=function(...) local f=make(...); f.SetFrameStrata=function(s,v) s.testStrata=v end; f.SetClampedToScreen=function(s,v) s.testClamped=v end; f.SetToplevel=function(s,v) s.testTop=v end; f.Raise=function(s) s.testRaised=true end; return f end; BuffTap:Options(); BuffTap:ShowWelcome(true); assert(BuffTap.options.testStrata=='DIALOG' and BuffTap.options.testTop and BuffTap.options.testClamped and BuffTap.options.testRaised); assert(BuffTap.welcome.testStrata=='FULLSCREEN_DIALOG' and BuffTap.welcome.testRaised and BuffTap.welcome.testClamped); assert(BuffTap.welcome.banner.parent==BuffTap.welcome and BuffTap.welcome.binding.parent==BuffTap.welcome and BuffTap.welcome.steps[1].parent==BuffTap.welcome)")
print('ALL',len(tests),'SCENARIOS PASSED')
