from test_minimap import test, tests, ROOT
modern="""
playerClass='WARRIOR'; spells={}; book={};
Enum.WeaponSlot={MainHand=0,OffHand=1}; Enum.ItemEnchantType={None=0,Permanent=1,Temporary=2,Imbue=3}
enchantLists={[0]={},[1]={}}
C_Item.GetWeaponEnchantInfo=function(slot) assert(slot==0 or slot==1); return enchantLists[slot] end
BuffTap.db.weaponApply=true; BuffTap.db.weaponCoatings.main='wizard-oil'
equipWeapon(16,9001); stock(20750,25121)
function coat(slot,id,remaining,kind) enchantLists[slot]={{hasEnchant=true,enchantType=kind or 2,enchantID=id,timeLeft=remaining*1000}} end
"""
test('No temporary coating preferences are enabled by default', "assert(not next(BuffTap.db.weaponCoatings)); assert(not BuffTap:CoatingPreference('main'))")
test('All-class oil prepares secure item and mainhand slot', modern+"refresh(); assert(BuffTap.action.coating and BuffTap.action.itemID==20750 and not BuffTap.action.manual); assert(BuffTap.button.attrs['target-slot']==16 and BuffTap.button.attrs.item=='item:20750')")
test('Oil expiry is category-specific and schedules wake without polling',modern+"coat(0,2627,100); refresh(); assert(not BuffTap.action and liveTimers()==1); C_Item.GetWeaponEnchantInfo=function(slot) return {{hasEnchant=true,enchantType=2,enchantID=2627,timeLeft=math.max(0,(200-now)*1000)}} end; advance(41); assert(BuffTap.action.coating and BuffTap.action.needState=='expiring'); BuffTap:ResetStats(); local n=BuffTap.stats.refreshes; advance(10); assert(BuffTap.stats.refreshes==n)")
test('Wrong recognized oil preserved until replacement opt-in',modern+"coat(0,2628,3600); refresh(); assert(not BuffTap.action); BuffTap.db.weaponReplace=true; refresh(); assert(BuffTap.action.itemID==20750 and BuffTap.action.needState=='different')")
test('Unknown temporary enchant never overwritten automatically',modern+"coat(0,9999,3600); refresh(); assert(not BuffTap.action); BuffTap.db.weaponReplace=true; refresh(); assert(BuffTap.action.manual and not next(bindings))")
test('Oil stock disappears before click clearing payload and binding',modern+"refresh(); bags[20750]=0; BuffTap.button.scripts.PreClick(nil,'LeftButton',true); assert(not BuffTap.action and not BuffTap.button.attrs.item and not next(bindings))")
test('Coating preference change invalidates prepared item',modern+"refresh(); BuffTap.db.weaponCoatings.main='frost-oil'; BuffTap.button.scripts.PreClick(nil,'LeftButton',true); assert(not BuffTap.action and not next(bindings))")
test('Weapon swap invalidates prepared oil',modern+"refresh(); equipWeapon(16,9002); BuffTap.button.scripts.PreClick(nil,'LeftButton',true); assert(not BuffTap.action)")
test('Poison and oil retain independent reminders',modern+"playerClass='ROGUE'; spell(8679,'Instant Poison'); BuffTap.db.weaponChoices.main='instant-poison'; BuffTap.db.weaponOffHand=false; stock(6947,8679); coat(0,2627,3600,2); refresh(); assert(BuffTap.action.itemID==6947); coat(0,323,3600,3); refresh(); assert(BuffTap.action.itemID==20750); table.insert(enchantLists[0],{hasEnchant=true,enchantType=2,enchantID=2627,timeLeft=3600000}); refresh(); assert(not BuffTap.action)")
test('Shaman imbue and oil are tracked independently',modern+"playerClass='SHAMAN'; spell(8232,'Windfury Weapon'); BuffTap.db.weaponChoices.main='windfury'; coat(0,283,3600,3); refresh(); assert(BuffTap.action.itemID==20750); table.insert(enchantLists[0],{hasEnchant=true,enchantType=2,enchantID=2627,timeLeft=3600000}); refresh(); assert(not BuffTap.action)")
test('Offhand oil uses exact offhand and ignores shield',modern+"BuffTap.db.weaponCoatings.main=nil; BuffTap.db.weaponCoatings.off='wizard-oil'; equipWeapon(17,9002); refresh(); assert(BuffTap.action.slot==17 and BuffTap.button.attrs['target-slot']==17); equipShield(17,9003); refresh(); assert(not BuffTap.action)")
test('Sharpening stone chooses highest carried usable rank',modern+"BuffTap.db.weaponCoatings.main='sharpening-stone'; stock(12404,16138); stock(7964,9900); items[12404].usable=false; refresh(); assert(BuffTap.action.itemID==7964)")
test('Weightstone rejected on sword and supported on mace',modern+"BuffTap.db.weaponCoatings.main='weightstone'; stock(12643,16622); refresh(); assert(not BuffTap.action); local old=C_Item.GetItemInfoInstant; C_Item.GetItemInfoInstant=function(id) if id==9001 then return id,'Weapon','Mace','INVTYPE_WEAPONMAINHAND',135274,2,4 end return old(id) end; refresh(); assert(BuffTap.action.itemID==12643)")
test('Ranged weapon fishing pole and held item never receive oil',modern+"local old=C_Item.GetItemInfoInstant; C_Item.GetItemInfoInstant=function(id) if id==9001 then return id,'Weapon','Wand','INVTYPE_RANGEDRIGHT',135274,2,19 end return old(id) end; refresh(); assert(not BuffTap.action); C_Item.GetItemInfoInstant=function(id) return id,'Weapon','Fishing','INVTYPE_2HWEAPON',135274,2,20 end; refresh(); assert(not BuffTap.action)")
test('Secret equipment subclass fails closed',modern+"C_Item.GetItemInfoInstant=function(id) return id,'Weapon','','INVTYPE_WEAPON',135274,2,{secret=true} end; refresh(); assert(not BuffTap.action and not next(bindings))")
test('Modern unavailable or secret data never becomes oil action',modern+"C_Item.GetWeaponEnchantInfo=nil; refresh(); assert(not BuffTap.action); C_Item.GetWeaponEnchantInfo=function() return {{secret=true}} end; refresh(); assert(not BuffTap.action)")
test('Changed item spell is rejected',modern+"items[20750].spell=9999; refresh(); assert(BuffTap.action.manual and not next(bindings))")
test('Manual mode gives oil alert without a casting binding',modern+"BuffTap.db.weaponApply=false; refresh(); assert(BuffTap.action.coating and BuffTap.action.manual and not next(bindings))")
test('Selected coating settings sanitize and preserve valid preferences',modern+"BuffTap.db.weaponCoatings={main='wizard-oil',off='bad',bad='wizard-oil'}; BuffTap:InitDB(); assert(BuffTap.db.weaponCoatings.main=='wizard-oil' and not BuffTap.db.weaponCoatings.off and not BuffTap.db.weaponCoatings.bad)")
test('Shared oil supply counts applications once without bank queries',modern+"equipWeapon(17,9002); BuffTap.db.weaponCoatings.off='wizard-oil'; BuffTap.db.suppliesEnabled=true; BuffTap.supplyInventoryReady=true; local old=C_Item.GetItemCount; C_Item.GetItemCount=function(id,bank,uses,rb,ab) assert(not bank and not rb and not ab); if id==20750 then return uses and 3 or 1 end return old(id,bank,uses,rb,ab) end; BuffTap:InvalidateSupplies(true); local rows=BuffTap:SyncSupplies(true); assert(#rows==1 and rows[1].count==3 and rows[1].key=='coating:wizard-oil')")
test('Oil-use cache cannot reuse bottle-count cache',modern+"BuffTap:InvalidateSupplies(true); C_Item.GetItemCount=function(id,bank,uses) return uses and 3 or 1 end; assert(BuffTap:SupplyCount(20750)==1 and BuffTap:SupplyCount(20750,true)==3)")
test('Weapons UI shows bounded coating selectors for every class',modern+"local old=CreateFrame; CreateFrame=function(...) local c=old(...); c.SetSize=function(self,w,h) self.width=w; self.height=h end; return c end; BuffTap:Options(); local f=BuffTap.options; assert(f.coatingPickers.main.menu.height==242 and #f.coatingPickers.main.menu.rows==13 and not f.weaponPickers.main.shown)")
test('Combat clears prepared oil with no insecure protected writes',modern+"refresh(); combat=true; safety('blocked'); BuffTap.events.scripts.OnEvent(nil,'PLAYER_REGEN_DISABLED'); assert(not BuffTap.action and not next(bindings)); combat=false; safety('ready'); BuffTap.events.scripts.OnEvent(nil,'PLAYER_REGEN_ENABLED'); assert(BuffTap.action.itemID==20750)")
test('Every catalog item prepares and recognizes its own verified enchant',modern+"local info=C_Item.GetItemInfoInstant; for _,choice in ipairs(BuffTap.CoatingChoices) do for n,pair in ipairs(choice.items) do bags={}; stock(pair[1],pair[2]); local subclass=7; if choice.subclasses~=0 then for i=0,19 do if math.floor(choice.subclasses/2^i)%2==1 then subclass=i; break end end end; C_Item.GetItemInfoInstant=function(id) if id==9001 then return id,'Weapon','','INVTYPE_WEAPONMAINHAND',135274,2,subclass end return info(id) end; BuffTap.db.weaponCoatings.main=choice.key; enchantLists[0]={}; refresh(); assert(BuffTap.action.itemID==pair[1] and BuffTap.action.id==pair[2] and not BuffTap.action.manual,choice.key); coat(0,choice.enchants[n],3600); refresh(); assert(not BuffTap.action,choice.key) end end")
test('Out-of-stock mainhand coating diagnostics and options stay usable',modern+"bags[20750]=0; refresh(); assert(BuffTap.action.manual and BuffTap.action.targetName=='Main hand'); local lines=BuffTap:DiagnosticsLines(); assert(lines[2]:find('Main hand',1,true)); BuffTap:Options()")
test('Offhand coating includes hand label in diagnostics',modern+"BuffTap.db.weaponCoatings.main=nil; BuffTap.db.weaponCoatings.off='wizard-oil'; equipWeapon(17,9002); refresh(); assert(BuffTap.action.targetName=='Off hand'); assert(BuffTap:DiagnosticsLines()[2]:find('Off hand',1,true))")
test('Diagnostics tolerate incomplete action display metadata',"BuffTap.action={reason='test'}; assert(BuffTap:DiagnosticsLines()[2]:find('Unknown target',1,true))")

print(f'ALL {len(tests)} SCENARIOS PASSED')
(ROOT/'tests/regression-coatings-latest.txt').write_text('\n'.join('PASS '+n for n in tests)+f'\n{len(tests)} mocked Lua 5.1 scenarios passed. Live weapon application and stacking checks pending.\n',encoding='utf-8')


