from test_coatings import test, tests, ROOT, modern
mage=modern+'''
playerClass='MAGE'; BuffTap.db.weaponCoatings.main=nil
BuffTap.db.weaponChoices.main='mage-imbue-lesser-flame'
local instant=C_Item.GetItemInfoInstant
C_Item.GetItemInfoInstant=function(id) if id==9001 then return id,'Weapon','','INVTYPE_2HWEAPON',135274,2,10 end return instant(id) end
stock(274947,1295720)
'''
test('Mage scroll preferences default to None',modern+"playerClass='MAGE'; BuffTap.db.weaponCoatings.main=nil; refresh(); assert(not BuffTap.action)")
test('Mage staff scroll uses mainhand secure item action',mage+"refresh(); assert(BuffTap.action.itemID==274947 and not BuffTap.action.manual and BuffTap.button.attrs['target-slot']==16)")
test('Mage active matching imbue satisfies preference',mage+"coat(0,8700,3600,3); refresh(); assert(not BuffTap.action)")
test('Mage unknown imbue is preserved even with replacement enabled',mage+"coat(0,99999,3600,3); refresh(); assert(not BuffTap.action); BuffTap.db.weaponReplace=true; refresh(); assert(BuffTap.action.manual and not next(bindings))")
test('Mage wrong weapon never prepares scroll',mage+"C_Item.GetItemInfoInstant=function(id) return id,'Weapon','','INVTYPE_WEAPON',135274,2,7 end; refresh(); assert(not BuffTap.action)")
test('Mage offhand is never used for scrolls',mage+"BuffTap.db.weaponMainHand=false; BuffTap.db.weaponChoices.off='mage-imbue-lesser-flame'; equipWeapon(17,9002); refresh(); assert(not BuffTap.action)")
test('Mage manual mode has no application binding',mage+"BuffTap.db.weaponApply=false; refresh(); assert(BuffTap.action.manual and not next(bindings))")
test('Mage missing modern categories cannot authorize item action',mage+"C_Item.GetWeaponEnchantInfo=nil; refresh(); assert(not BuffTap.action or BuffTap.action.manual)")
test('Mage scroll stock change before click clears secure action',mage+"refresh(); bags[274947]=0; BuffTap.button.scripts.PreClick(nil,'LeftButton',true); assert(not BuffTap.action and not next(bindings))")
test('Mage preference change before click clears secure action',mage+"refresh(); BuffTap.db.weaponChoices.main='mage-imbue-frost'; BuffTap.button.scripts.PreClick(nil,'LeftButton',true); assert(not BuffTap.action)")
test('Mage bag restock updates idle reminder',mage+"bags[274947]=0; refresh(); assert(BuffTap.action.manual); bags[274947]=5; BuffTap.events.scripts.OnEvent(nil,'BAG_UPDATE_DELAYED'); advance(.2); assert(BuffTap.action.itemID==274947 and not BuffTap.action.manual)")
test('All-class oil bag restock updates idle reminder',modern+"bags[20750]=0; refresh(); assert(BuffTap.action.manual); bags[20750]=5; BuffTap.events.scripts.OnEvent(nil,'BAG_UPDATE_DELAYED'); advance(.2); assert(BuffTap.action.itemID==20750 and not BuffTap.action.manual)")
test('Mage scroll and oil categories stay independent',mage+"BuffTap.db.weaponCoatings.main='wizard-oil'; coat(0,8700,3600,3); refresh(); assert(BuffTap.action.itemID==20750); table.insert(enchantLists[0],{hasEnchant=true,enchantType=2,enchantID=2627,timeLeft=3600000}); refresh(); assert(not BuffTap.action)")
test('Mage supplies count selected compatible scroll',mage+"BuffTap.db.suppliesEnabled=true; BuffTap.supplyInventoryReady=true; BuffTap:InvalidateSupplies(true); local rows=BuffTap:SyncSupplies(true); assert(#rows==1 and rows[1].key=='imbue:mage-imbue-lesser-flame' and rows[1].count==5)")
test('Every verified Mage scroll prepares and recognizes exact imbue',mage+'''local count=0; for _,choice in ipairs(BuffTap.WeaponChoices) do if choice.class=='MAGE' then count=count+1; bags={}; stock(choice.items[1][1],choice.items[1][2]); local subclass=choice.subclasses==1024 and 10 or choice.subclasses==32768 and 15 or 7; C_Item.GetItemInfoInstant=function(id) return id,'Weapon','','INVTYPE_WEAPONMAINHAND',135274,2,subclass end; BuffTap.db.weaponChoices.main=choice.key; enchantLists[0]={}; refresh(); assert(BuffTap.action.itemID==choice.items[1][1] and not BuffTap.action.manual,choice.key); coat(0,choice.enchants[1],3600,3); refresh(); assert(not BuffTap.action,choice.key); assert(choice.items[1][1]~=277503) end end; assert(count==15)''')
test('Crippling Poison II is preferred and recognized',modern+"playerClass='ROGUE'; BuffTap.db.weaponCoatings.main=nil; BuffTap.db.weaponOffHand=false; BuffTap.db.weaponChoices.main='crippling-poison'; stock(3775,3408); stock(3776,11202); refresh(); assert(BuffTap.action.itemID==3776); coat(0,603,3600,3); refresh(); assert(not BuffTap.action)")
test('Metadata failure storm obeys backoff and finite attempts',"local calls=0; C_Item.RequestLoadItemDataByID=function() calls=calls+1 end; BuffTap:RequestItemData(999001); for i=1,100 do BuffTap.events.scripts.OnEvent(nil,'ITEM_DATA_LOAD_RESULT',999001,false) end; assert(calls==1); advance(10.1); assert(calls==2); advance(30); assert(calls==3); advance(120); assert(calls==3 and not BuffTap.timers['item-data:999001'])")
test('Metadata success cancels retry slot',"C_Item.RequestLoadItemDataByID=function() end; BuffTap:RequestItemData(999001); BuffTap.events.scripts.OnEvent(nil,'ITEM_DATA_LOAD_RESULT',999001,true); assert(not BuffTap.itemRequestState[999001] and not BuffTap.timers['item-data:999001'])")
test('Metadata retry suspends in combat and resumes afterward',"local calls=0; C_Item.RequestLoadItemDataByID=function() calls=calls+1 end; BuffTap:RequestItemData(999001); combat=true; safety('blocked'); BuffTap.events.scripts.OnEvent(nil,'PLAYER_REGEN_DISABLED'); assert(liveTimers()==0); advance(40); assert(calls==1); combat=false; safety('ready'); BuffTap.events.scripts.OnEvent(nil,'PLAYER_REGEN_ENABLED'); advance(.1); assert(calls==2)")
test('Retry reminders clears effect pause but keeps mapping quarantine',"BuffTap.effectPauses={[13510]=true}; BuffTap.itemQuarantine={[13512]='mapping changed'}; BuffTap:RetryConsumableReminders(); assert(not next(BuffTap.effectPauses) and BuffTap.itemQuarantine[13512])")
test('Delayed flask aura avoids effect pause',"stock(13510,17626); consumables('flask'); refresh(); BuffTap.button.scripts.PreClick(nil,'LeftButton',false); bags[13510]=4; BuffTap.button.scripts.PostClick(nil,'LeftButton',false); advance(7); aura('player',17626,'Titans',3600,7200); advance(5); assert(not BuffTap.effectPauses or not BuffTap.effectPauses[13510]); assert(not BuffTap.action)")
test('Explicit retry restores paused consumable without casting',"stock(13510,17626); consumables('flask'); refresh(); BuffTap.button.scripts.PreClick(nil,'LeftButton',false); bags[13510]=4; BuffTap.button.scripts.PostClick(nil,'LeftButton',false); advance(11); assert(BuffTap.effectPauses[13510]); BuffTap:RetryConsumableReminders(); advance(.1); assert(BuffTap.action.itemID==13510 and bags[13510]==4)")
test('Mage picker is bounded and includes None plus fifteen choices',mage+"local old=CreateFrame; CreateFrame=function(...) local c=old(...); c.SetSize=function(self,w,h) self.width=w; self.height=h end; return c end; BuffTap:Options(); assert(BuffTap.options.weaponPickers.main.menu.height==242 and #BuffTap.options.weaponPickers.main.menu.rows==16)")
test('Unobserved Auto flask pauses all alternatives',"stock(13510,17626); stock(13512,17628); consumables('flask'); refresh(); local used=BuffTap.action.itemID; BuffTap.button.scripts.PreClick(nil,'LeftButton',false); bags[used]=4; BuffTap.button.scripts.PostClick(nil,'LeftButton',false); advance(11); assert(BuffTap.effectPauses[used] and not BuffTap.action); refresh(); assert(not BuffTap.action)")
test('Native metadata request throws stop after three attempts',"local calls=0; C_Item.RequestLoadItemDataByID=function() calls=calls+1; error('unavailable') end; BuffTap:RequestItemData(999001); advance(150); assert(calls==3 and not BuffTap.timers['item-data:999001'])")
test('Retry clears failed item metadata cache and allows another request',"local calls=0; C_Item.RequestLoadItemDataByID=function() calls=calls+1 end; BuffTap:RequestItemData(999001); advance(150); BuffTap.itemMeta={[999001]={loaded=false}}; BuffTap:RetryConsumableReminders(); assert(not BuffTap.itemMeta[999001]); BuffTap:RequestItemData(999001); assert(calls==4)")
test('Requested item completion invalidates Healthstone inventory cache',"C_Item.RequestLoadItemDataByID=function() end; BuffTap:RequestItemData(999001); local cached={}; BuffTap.readinessInventory=cached; BuffTap.events.scripts.OnEvent(nil,'ITEM_DATA_LOAD_RESULT',999001,true); assert(BuffTap.readinessInventory~=cached)")
for locale in ['esES','deDE','frFR','ptBR']:
 test('Retry controls localized '+locale,"assert(BuffTap:Text('Retry reminders')~='Retry reminders')",locale)
print(f'ALL {len(tests)} SCENARIOS PASSED')
(ROOT/'tests/last-run-1.8.0.txt').write_text('\n'.join('PASS '+n for n in tests)+f'\n{len(tests)} mocked Lua 5.1 scenarios passed. Live Mage application remains unverified.\n',encoding='utf-8')
