from test_mouse_bindings import test
from test_bufftap import tests

modern='''
playerClass='ROGUE'; spells={}; book={};
Enum.WeaponSlot={MainHand=0,OffHand=1}; Enum.ItemEnchantType={None=0,Permanent=1,Temporary=2,Imbue=3}
enchantLists={[0]={},[1]={}}
C_Item.GetWeaponEnchantInfo=function(slot) assert(slot==0 or slot==1); return enchantLists[slot] end
BuffTap.db.weaponApply=true; BuffTap.db.weaponChoices.main='instant-poison'; BuffTap.db.weaponChoices.off='deadly-poison'
equipWeapon(16,9001); equipWeapon(17,9002); stock(6947,8679); stock(2892,2823)
function coating(hand,id,remaining,kind)
 enchantLists[hand]={{hasEnchant=true,enchantType=kind or 3,enchantID=id,timeLeft=remaining*1000}}
end
'''

test('New application is opt-in and class preferences sanitize', "assert(BuffTap.db.weaponApply==false); BuffTap.db.weaponChoices={main='invalid',off='rockbiter',bad='instant-poison'}; BuffTap.db.weaponSeconds=0/0; BuffTap:InitDB(); assert(not next(BuffTap.db.weaponChoices) and BuffTap.db.weaponSeconds==60)")
test('Modern poison uses item action and exact main slot',modern+"refresh(); assert(BuffTap.action.itemID==6947 and not BuffTap.action.manual); assert(BuffTap.button.attrs.type1=='item' and BuffTap.button.attrs.item=='item:6947' and BuffTap.button.attrs['target-slot']==16 and bindings.MOUSEWHEELDOWN)")
test('Poison hand progression updates same secure payload slot',modern+"BuffTap.db.weaponChoices.off='instant-poison'; refresh(); coating(0,323,3600); refresh(); assert(BuffTap.action.slot==17 and BuffTap.button.attrs['target-slot']==17 and BuffTap.button.attrs.item=='item:6947')")
test('Preferred poison chooses highest usable carried rank',modern+"stock(8928,11340); refresh(); assert(BuffTap.action.itemID==8928); items[8928].usable=false; refresh(); assert(BuffTap.action.itemID==6947)")
test('Empty poison bags retain preference and manual alert',modern+"bags[6947]=0; bags[2892]=0; refresh(); assert(BuffTap.action.manual and not next(bindings)); assert(BuffTap.db.weaponChoices.main=='instant-poison'); assert(BuffTap.action.reason:find('out of stock'))")
test('Poison stock disappears before click and clears slot',modern+"refresh(); bags[6947]=0; BuffTap.button.scripts.PreClick(nil,'LeftButton',true); assert(not BuffTap.action and not BuffTap.button.attrs['target-slot'] and not next(bindings))")
test('Weapon swap before click clears stale slot action',modern+"refresh(); equipWeapon(16,9999); BuffTap.button.scripts.PreClick(nil,'LeftButton',true); assert(not BuffTap.action and not BuffTap.button.attrs.item)")
test('Preference change before click rejects old poison',modern+"refresh(); BuffTap.db.weaponChoices.main='deadly-poison'; BuffTap.button.scripts.PreClick(nil,'LeftButton',true); assert(not BuffTap.action)")
test('Correct poison remains active until threshold',modern+"BuffTap.db.weaponOffHand=false; coating(0,323,100); refresh(); assert(not BuffTap.action and liveTimers()==1); C_Item.GetWeaponEnchantInfo=function(slot) return {{hasEnchant=true,enchantType=3,enchantID=323,timeLeft=math.max(0,(200-now)*1000)}} end; advance(41); assert(BuffTap.action and BuffTap.action.needState=='expiring' and not BuffTap.action.manual)")
test('Expiring poison does not cause continuous refresh polling',modern+"BuffTap.db.weaponOffHand=false; coating(0,323,30); BuffTap:ResetStats(); refresh(); local before=BuffTap.stats.refreshes; advance(10); assert(BuffTap.stats.refreshes==before and liveTimers()==1)")
test('Wrong poison preserved unless replacement opted in',modern+"BuffTap.db.weaponOffHand=false; coating(0,7,3600); refresh(); assert(not BuffTap.action); BuffTap.db.weaponReplace=true; refresh(); assert(BuffTap.action.itemID==6947 and BuffTap.action.needState=='different')")
test('Permanent enchant never satisfies poison requirement',modern+"coating(0,9999,3600,1); refresh(); assert(BuffTap.action.itemID==6947)")
test('Unknown coating uses manual fallback without consuming poison',modern+"coating(0,9999,3600,2); BuffTap.db.weaponOffHand=false; refresh(); assert(BuffTap.action.manual and not next(bindings) and bags[6947]==5)")
test('Recognized poison can coexist with another temporary coating',modern+"coating(0,323,3600,3); table.insert(enchantLists[0],{hasEnchant=true,enchantType=2,enchantID=9999,timeLeft=3600000}); BuffTap.db.weaponOffHand=false; refresh(); assert(not BuffTap.action)")
test('Secret modern enchant records fail closed',modern+"enchantLists[0]={{secret=true}}; BuffTap.db.weaponOffHand=false; refresh(); assert(not BuffTap.action and not next(bindings)); assert(BuffTap:WeaponCoatingState(16).known==false)")
test('Modern API failure never falls back to contradictory legacy data',modern+"C_Item.GetWeaponEnchantInfo=function() error('unavailable') end; BuffTap.db.weaponOffHand=false; refresh(); assert(not BuffTap.action)")
test('Unreadable main hand does not hide definite offhand need',modern+"enchantLists[0]={{secret=true}}; refresh(); assert(BuffTap.action.itemID==2892 and BuffTap.action.slot==17)")
test('Shaman uses highest learned preferred imbue on main hand',modern+"playerClass='SHAMAN'; equipped[17]=nil; spell(8017,'Rockbiter Weapon'); spell(8018,'Rockbiter Weapon'); BuffTap.db.weaponChoices.main='rockbiter'; refresh(); assert(BuffTap.action.id==8018 and BuffTap.button.attrs.type1=='spell' and BuffTap.button.attrs['target-slot']==16)")
test('Shaman oil cannot hide missing imbue and shield excluded',modern+"playerClass='SHAMAN'; equipShield(17,9003); spell(8232,'Windfury Weapon'); BuffTap.db.weaponChoices.main='windfury'; coating(0,9999,3600,2); refresh(); assert(BuffTap.action.id==8232 and not BuffTap.action.manual); BuffTap:Options(); assert(not BuffTap.options.weaponOff.shown and not BuffTap.options.weaponPickers.off.shown)")
test('Shaman correct imbue satisfies main hand only',modern+"playerClass='SHAMAN'; equipShield(17,9003); spell(8232,'Windfury Weapon'); BuffTap.db.weaponChoices.main='windfury'; coating(0,283,3600); refresh(); assert(not BuffTap.action)")
test('Unlearned Shaman preference stays manual rather than choosing another',modern+"playerClass='SHAMAN'; equipped[17]=nil; spell(8232,'Windfury Weapon'); BuffTap.db.weaponChoices.main='rockbiter'; refresh(); assert(BuffTap.action.manual and BuffTap.action.reason:find('not learned') and not next(bindings))")
test('Shaman missing offhand never receives scroll action',modern+"playerClass='SHAMAN'; spell(8232,'Windfury Weapon'); BuffTap.db.weaponChoices.main='windfury'; BuffTap.db.weaponChoices.off='windfury'; coating(0,283,3600); refresh(); assert(not BuffTap.action)")
test('Weapon application releases payload and bindings in combat',modern+"refresh(); combat=true; safety('blocked'); BuffTap.events.scripts.OnEvent(nil,'PLAYER_REGEN_DISABLED'); assert(not next(bindings) and not BuffTap.button.attrs['target-slot'] and not BuffTap.button.attrs.item); combat=false; safety('ready'); BuffTap.events.scripts.OnEvent(nil,'PLAYER_REGEN_ENABLED'); assert(BuffTap.action and bindings.MOUSEWHEELDOWN)")
test('Switching from poison to aura clears weapon target-slot',modern+"refresh(); playerClass='DRUID'; seed(); refresh(); assert(BuffTap.action.id==5232 and not BuffTap.button.attrs['target-slot'] and not BuffTap.button.attrs.item)")
test('Weapon click settling prevents duplicate applications',modern+"refresh(); BuffTap.button.scripts.PostClick(nil,'LeftButton',true); refresh(); assert(not BuffTap.action); advance(4); assert(not BuffTap.action); coating(0,323,3600); coating(1,7,3600); advance(1.2); assert(not BuffTap.action)")
test('Rogue weapon selectors display inventory availability',modern+"BuffTap:Options(); assert(BuffTap.options.weaponPickers.main.shown and BuffTap.options.weaponPickers.off.shown); assert(BuffTap.options.weaponPickers.main.menu.rows[2].text:find('in bags: 5'))")
test('Shaman options never alter a Rogue offhand setting',modern+"playerClass='SHAMAN'; equipped[17]=nil; BuffTap:Options(); assert(BuffTap.db.weaponOffHand==true and not BuffTap.options.weaponOff.shown)")
test('No weapon application when disabled',modern+"BuffTap.db.weaponApply=false; spell(8679,'Instant Poison'); refresh(); assert(BuffTap.action.manual and not next(bindings))")
test('Cooldown delays poison application until ready',modern+"BuffTap.db.weaponOffHand=false; C_Item.GetItemCooldown=function() return 100,10,true end; refresh(); assert(not BuffTap.action and liveTimers()==1); advance(10.2); assert(BuffTap.action and not BuffTap.action.manual)")
test('Poison without usable metadata cannot arm a binding',modern+"items[6947].loaded=false; bags[2892]=0; refresh(); assert(BuffTap.action.manual and not next(bindings))")
test('Bag restock refreshes weapon actions with other item features off',modern+"BuffTap.db.weaponOffHand=false; bags[6947]=0; refresh(); assert(BuffTap.action.manual); bags[6947]=5; BuffTap.events.scripts.OnEvent(nil,'BAG_UPDATE_DELAYED'); advance(.2); assert(BuffTap.action.itemID==6947 and not BuffTap.action.manual)")
test('Weapon metadata load event restores a ready poison',modern+"BuffTap.db.weaponOffHand=false; items[6947].loaded=false; refresh(); assert(BuffTap.itemRequests[6947] and BuffTap.action.manual); items[6947].loaded=true; BuffTap.events.scripts.OnEvent(nil,'ITEM_DATA_LOAD_RESULT',6947,true); advance(.2); assert(BuffTap.action and not BuffTap.action.manual)")
test('Fishing pole is excluded from weapon applications',modern+"BuffTap.db.weaponOffHand=false; C_Item.GetItemInfoInstant=function(id) return id,'Weapon','Fishing Pole','INVTYPE_2HWEAPON',135274,2,20 end; refresh(); assert(not BuffTap.action)")
test('Expired preferred poison schedules missing application without another event',modern+"BuffTap.db.weaponOffHand=false; BuffTap.db.weaponSeconds=0; C_Item.GetWeaponEnchantInfo=function(slot) return {{hasEnchant=now<110,enchantType=3,enchantID=323,timeLeft=math.max(0,(110-now)*1000)}} end; refresh(); assert(not BuffTap.action); advance(10.2); assert(BuffTap.action and BuffTap.action.needState=='missing')")
test('Turning weapon application off clears targeted secure action',modern+"spell(8679,'Instant Poison'); refresh(); BuffTap.db.weaponApply=false; refresh(); assert(BuffTap.action.manual and not BuffTap.button.attrs['target-slot'] and not BuffTap.button.attrs.item and not next(bindings))")
test('Weapon selector saves exact chosen family and closes menu',modern+"BuffTap:Options(); local row=BuffTap.options.weaponPickers.main.menu.rows[3]; row.scripts.OnClick(row); advance(.1); assert(BuffTap.db.weaponChoices.main=='deadly-poison' and BuffTap.action.itemID==2892 and not BuffTap.options.weaponPickers.main.menu.shown)")
test('Shaman with two-handed weapon remains castable',modern+"playerClass='SHAMAN'; equipped[17]=nil; items[9001].equipLoc='INVTYPE_2HWEAPON'; spell(8232,'Windfury Weapon'); BuffTap.db.weaponChoices.main='windfury'; refresh(); assert(BuffTap.action.id==8232 and not BuffTap.action.manual)")
test('Changed poison item effect mapping never becomes a secure action',modern+"BuffTap.db.weaponOffHand=false; items[6947].spell=99999; refresh(); assert(BuffTap.action.manual and not next(bindings))")
test('Unknown Shaman imbue is not replaced through scroll',modern+"playerClass='SHAMAN'; equipped[17]=nil; spell(8232,'Windfury Weapon'); BuffTap.db.weaponChoices.main='windfury'; BuffTap.db.weaponReplace=true; coating(0,99999,3600); refresh(); assert(BuffTap.action.manual and not next(bindings))")

test('Uncached poison spell data requests loading and recovers',modern+"BuffTap.db.weaponOffHand=false; local original=C_Item.GetItemSpell; C_Item.GetItemSpell=function() return nil,nil end; local loads=0; C_Item.RequestLoadItemDataByID=function() loads=loads+1 end; refresh(); assert(BuffTap.action.manual and loads==1 and type(BuffTap.itemRequests[6947])=='number'); C_Item.GetItemSpell=original; BuffTap.events.scripts.OnEvent(nil,'ITEM_DATA_LOAD_RESULT',6947,true); advance(.1); assert(BuffTap.action.itemID==6947 and not BuffTap.action.manual)")
test('Weapon and discovery metadata requests share timestamps',modern+"items[6947].loaded=false; BuffTap:WeaponChoiceSource(BuffTap:WeaponChoice('instant-poison')); assert(type(BuffTap.itemRequests[6947])=='number'); local ok=pcall(BuffTap.ConsumableItemInfo,BuffTap,6947); assert(ok)")
test('Unknown class preserves valid saved weapon preferences',modern+"local original=UnitClass; UnitClass=function() return nil,nil end; BuffTap:InitDB(); assert(BuffTap.db.weaponChoices.main=='instant-poison' and BuffTap.db.weaponChoices.off=='deadly-poison'); UnitClass=original; BuffTap:InitDB(); assert(BuffTap.db.weaponChoices.main=='instant-poison')")
test('Failed metadata request can retry',modern+"items[6947].loaded=false; C_Item.RequestLoadItemDataByID=function() error('unavailable') end; BuffTap:WeaponChoiceSource(BuffTap:WeaponChoice('instant-poison')); assert(not BuffTap.itemRequests[6947]); local loads=0; C_Item.RequestLoadItemDataByID=function() loads=loads+1 end; BuffTap:WeaponChoiceSource(BuffTap:WeaponChoice('instant-poison')); assert(loads==0); advance(10.1); assert(loads==1)")
test('Weapons precedes Appearance and shortcuts select correct pages',modern+"BuffTap:Options(); assert(BuffTap.options.tabs[5].text=='Weapons' and BuffTap.options.tabs[6].text=='Appearance'); BuffTap:HelperOptions(); assert(BuffTap.options.activeTab==7 and BuffTap.helperWindow:IsShown()); BuffTap.options.selectTab(5); assert(BuffTap.options.weaponTitle.parent==BuffTap.options.pages[5] or BuffTap.options.pages[5]:IsShown())")
test('Other classes expose temporary coatings without poison controls',"BuffTap:Options(); local f=BuffTap.options; assert(not f.weaponUnavailable.shown and f.weaponTimingLabel.shown and not f.weaponPoisonHint.shown and f.weaponHandsHint.shown and not f.weaponPickers.main.shown and f.coatingPickers.main)")

print(f'ALL {len(tests)} SCENARIOS PASSED')
